KAKAO:
  REDIRECT:
    URI : http://localhost:8080/api/auth/kakao/callback
  REST:
    API:
      KEY: 6c942efa99c45588cbc84327554939d5

NAVER:
  CLIENT:
    ID: r3TXBYYIMC1QuDnvxaja
    SECRET: 3hTsQmrNtr
  REDIRECT:
    URI: http://localhost:8080/auth/naver/login